### ISSUE TITLE
Fails to decode JWT

### ISSUE THREAD

**Issue by ajgarlag** [krkabol/OAuth_reproducer#4]
The client app fails with this message: "Error decoding JWT: Path cannot be empty".

The property `jwksUri` is not defined.

https://github.com/krkabol/OAuth_reproducer/blob/a9fe1da5b05a4d28fd9f7d50ab7b4b5c6dcec797/OAuthTestClient/app.php#L137

**Comment by krkabol** [comment]
#

**Comment by krkabol** [comment]
fixed in d57d9775
